name: 'Home Assistant helper: version-push'
description: 'GitHub action helper: version-push'
inputs:
  key:
    required: true
    default: ''
    description: "JSON key to replace version with, e.g. supervisor, homeassistant.default or hassos[] to replace for all properties in hassos."
  key-description:
    required: false
    description: "Human Friendly description of key which is being changed for git commit message."
  version:
    required: true
    default: ''
  channel:
    default: 'dev'
  rollout:
    required: false
    default: 'false'
    description: "Generate rollout description file for staged rollout"
  create-pr:
    required: false
    default: 'false'
    description: "Whether to create a new branch and open a pull request"
runs:
  using: "composite"
  steps:
    - shell: bash
      id: validate-input
      env:
        INPUTS_KEY: ${{ inputs.key }}
        INPUTS_VERSION: ${{ inputs.version }}
        INPUTS_KEY_DESCRIPTION: ${{ inputs.key-description }}
      run: |
        if [[ -z "$INPUTS_KEY" ]];then
          echo "::error::Missing required key 'key' input!"
          exit 1
        elif [[ -z "$INPUTS_VERSION" ]];then
          echo "::error::Missing required key 'version' input!"
          exit 1
        fi
        if [[ -z "$INPUTS_KEY_DESCRIPTION" ]];then
          echo "key-description=$INPUTS_KEY" >> "$GITHUB_OUTPUT"
        else
          echo "key-description=$INPUTS_KEY_DESCRIPTION" >> "$GITHUB_OUTPUT"
        fi

    - shell: bash
      env:
        INPUTS_CHANNEL: ${{ inputs.channel }}
      run: git clone --depth 1 --single-branch --branch "$INPUTS_CHANNEL" https://github.com/agners/home-assistant-version.git /tmp/version

    - shell: bash
      working-directory: /tmp/version
      if: ${{ inputs.create-pr == 'true' }}
      env:
        INPUTS_KEY: ${{ inputs.key }}
        INPUTS_VERSION: ${{ inputs.version }}
      run: |
        branch_name="update/${{ inputs.key }}-${{ inputs.version }}"
        git checkout -b "$branch_name"

    - shell: bash
      working-directory: /tmp/version
      env:
        INPUTS_KEY: ${{ inputs.key }}
        INPUTS_VERSION: ${{ inputs.version }}
      run: |
        temp=$(mktemp)
        jq ".$INPUTS_KEY |= \"$INPUTS_VERSION\"" "version.json" > "${temp}"
        mv "${temp}" "version.json"

    - name: Generate rollout plan JSON
      working-directory: /tmp/version
      if: ${{ inputs.rollout == 'true' }}
      shell: python
      run: |
          import json
          from datetime import datetime, timedelta

          # Define the timespan/percentage tuples: (timespan in hours, target cumulative percentage)
          rollout_stages = [
              (1, 5),       # After 1 hour, reach 5% of users
              (48, 5),      # For 48 hours, stay at 5% of users
              (12, 100),     # After 12 more hours, reach 100% of users
          ]

          # Start from the current UTC time
          current_time = datetime.utcnow()
          rollout_plan = {}

          # Generate each stage in the rollout plan
          for timespan, target_percentage in rollout_stages:
              current_time += timedelta(hours=timespan)
              rollout_plan[current_time.isoformat() + 'Z'] = target_percentage

          # Write to JSON file
          with open('rollout.json', 'w') as f:
              json.dump(rollout_plan, f, indent=2)

          print('Rollout plan generated:', rollout_plan)

    - shell: bash
      working-directory: /tmp/version
      env:
        INPUTS_VERSION: ${{ inputs.version }}
      run: |
        git add version.json rollout.json
        git commit -m "Bump ${{ steps.validate-input.outputs.key-description }} to $INPUTS_VERSION"
        git push

    - name: Create Pull Request
      if: ${{ inputs.create-pr == 'true' }}
      uses: peter-evans/create-pull-request@v7.0.5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ inputs.channel }}
        head: "$(git rev-parse --abbrev-ref HEAD)"
        title: "Bump ${{ inputs.key-description }} to ${{ inputs.version }}"
        body: |
          This pull request updates ${{ inputs.key-description }} to version ${{ inputs.version }}.

    - shell: bash
      run: rm -rf /tmp/version

